# Generated by Django 4.1.4 on 2023-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=100)),
                ("name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
